### ISSUE TITLE
Menü maradjon nyitva mikor oldalt váltunk

### ISSUE THREAD

**Issue by Fulop-Krisztian** [Horribili-Fejlesztok/Horribili-KFT#14]

**Comment by kiss-csongor** [comment]
Megoldva 2023.10.26 17:53
Kisebb képernyőknél (pl telón) a menü nem tünik el, hogy a menü ne takarja ki az újonnan megjelenő oldalt
Közepes és nagyobb kijelzőkön (mivel ott már nem takar ki sokat a menü) ott a menüsáv nyitva marad
