### ISSUE TITLE
LEAGUE OF LEGENDS

### ISSUE THREAD

**Issue by Fulop-Krisztian** [Horribili-Fejlesztok/Horribili-KFT#16]
Az infinityfree webes hosztoló felhasználói feltételeiben benne van, hogy aki LEAGUE OF LEGENDS-et játszik, az elmehet melegebb éghajlatra.

Emiatt az oldalunkon nem szabad szerepelnie semminek, ami a játékra utalhat

Jelenleg csak egy helyen, a start.html-ben kell ezt orvosolni

**Comment by kiss-csongor** [comment]
Megoldva 2023.10.26 17:44
