### ISSUE TITLE
Az oldal frissítéskor tartsa meg a munkamenetet

### ISSUE THREAD

**Issue by Fulop-Krisztian** [Horribili-Fejlesztok/Horribili-KFT#20]
Arra gondolok, hogyha például a szolgáltatások oldalon vagyunk, és frissítünk egyet, akkor ne vigyen vissza a kezdőlapra, hanem maradjon a szolgáltatások weblapon

Valószínűleg ehhez sütiket kell használnunk

**Comment by kiss-csongor** [comment]
Megnézem mit tudok kihozni belőle

**Comment by kiss-csongor** [comment]
Próbálkoztam több fajta megoldással, de nekem nem jött össze, ha valakinek több türelme lesz hozzá lesse meg

**Comment by Fulop-Krisztian** [comment]
Megpróbálom megoldani

**Comment by Fulop-Krisztian** [comment]
Megoldva, nemsokára kerül fel a pull request

**Comment by Fulop-Krisztian** [comment]
Pull request mergelve
