### ISSUE TITLE
A teams oldal nem nyílik meg

### ISSUE THREAD

**Issue by Fulop-Krisztian** [Horribili-Fejlesztok/Horribili-KFT#28]
A teams oldal helyett egyből beugrik a kezdőlap. Egy pillanatra beugrik a teams.

Jelenleg az ok ismeretlen. Valószínűleg az új menü + az új kezdőlap kombinációja zavar valamit.

**Comment by kiss-csongor** [comment]
A teams oldalon be volt linkelve a main.js emiatt ott újra betöltötte alapértelmezetten a kezdőlapot, emiatt a teams oldal felé helyezte a start.html-t
