### ISSUE TITLE
Carouselek javítása

### ISSUE THREAD

**Issue by Fulop-Krisztian** [Horribili-Fejlesztok/Horribili-KFT#43]
Látom reszponzívan vannak megoldva a carouselek, de van pár gond a jelenlegi implementációval:

1. A header miatt (ami letolja az egész weboldalt var(--header-height) mennyiséggel) a carousel alja nem látszik, pedig az lenne a reszponzivitás célja
2. A képek nyúlnak és összenyomódnak aspect ratio változásával. Meg lehetne oldalni hogy a képek szélei csak levágódjanak különböző méretű kijelzőkön (az `object-fit: cover;` css beállítás azt hiszem ezt csinálja)

A képen látható mindkét probléma:
![image](https://github.com/Horribili-Fejlesztok/Horribili-KFT/assets/70952326/08324676-7326-487a-9e10-25cda67eb86a)

**Comment by kiss-csongor** [comment]
Megoldva, következő pull requesttel javítva lesz
