### ISSUE TITLE
A linkek oda vigyenek az oldalon ami releváns (kezdőlap)

### ISSUE THREAD

**Issue by Fulop-Krisztian** [Horribili-Fejlesztok/Horribili-KFT#59]
Itt például arra gondolok, hogy ha valaki telefonon megnyom egy linket a főoldalon hogy többet akar tudni a Nagy hálózatról, akkor nem oda viszi ahol a nagy hálózat van. Ezt ID-vel lehetne megoldani a href-be.
Hozzá is adok minden szolgáltatás kártyához egy id-t ami a tartalomnak megfelelő

A sikertörténeteink részt nem tudom mennyire nehéz megcsinálni, de ott is megnyithatná azt a carousel lapot, amire rákattintanak.

**Comment by Fulop-Krisztian** [comment]
IDk:
smallnetwork
mediumnetwork
largenetwork
pentagon

**Comment by kiss-csongor** [comment]
Próbálkoztam a carouselnél is, de nem akar működni, mert ott nem href-el megy az egész ott egy active class van azon a "dián", amelyik éppen megjelenik

**Comment by kiss-csongor** [comment]
kész
