### ISSUE TITLE
Szerepkörök bővítése

### ISSUE THREAD

**Issue by kizekzoltan** [Horribili-Fejlesztok/Horribili-KFT#67]
Dani kérlek a mai események után, ha van lehetőség, akkor kérlek írd be a kártyákhoz a következő munkaköröket: Csokesz - színész, Zoli- Színész, Flávi - operatőr, Krisz - lámpakezelő és hangmérnök. Köszönöm szépen!

**Comment by novakidaniel** [comment]
Kész van Zoli, remélem így jó lesz
